name: timer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  assets_audio_player: ^3.1.1
  audioplayers: ^5.2.1
  audioplayers_web: ^4.1.0
  cloud_firestore: ^4.13.2
  dynamic_color: ^1.6.8
  firebase_auth: ^4.15.3
  firebase_core: ^2.23.0
  firebase_database: ^10.3.5
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.1.0
  intl: ^0.18.1
  percent_indicator: ^4.2.3
  sidebarx: ^0.16.3
  staggered_grid_view_flutter: ^0.0.4
  time: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/

  # - assets/sound/sm64_coin.mp3
  # - assets/sound/assets/sound/sm64_coin.mp3