// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoECGAFivJkptwiN1hd8mZvjPx6_np18Q',
    appId: '1:587728103989:web:67f3184ce4d21577fd5f7c',
    messagingSenderId: '587728103989',
    projectId: 'timer-aeo',
    authDomain: 'timer-aeo.firebaseapp.com',
    databaseURL: 'https://timer-aeo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'timer-aeo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUYz2902bmy4pPmO4RQm56zaoTgtbKxzw',
    appId: '1:587728103989:android:48ebb359471f9a59fd5f7c',
    messagingSenderId: '587728103989',
    projectId: 'timer-aeo',
    databaseURL: 'https://timer-aeo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'timer-aeo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsK3EhyR44U2DuynuoT5bA4y4GAkLn9oM',
    appId: '1:587728103989:ios:6633123386749210fd5f7c',
    messagingSenderId: '587728103989',
    projectId: 'timer-aeo',
    databaseURL: 'https://timer-aeo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'timer-aeo.appspot.com',
    iosBundleId: 'com.example.timer',
  );
}
